import os
from typing import Dict, Any

VideoFeatures = Dict[str, Any]

VIDEO_EXTENSIONS = {'.mp4', '.mkv', '.avi', '.mov', '.webm'}

LENGTH_TOLERANCE = 0.25
DURATION_BUCKET_SIZE = 60
DURATION_BUCKET_ADJACENT = 1
FORCE_COMPARE_THRESHOLD = 600

AUDIO_SAMPLE_DURATION = 10
NUM_AUDIO_ANCHORS = 5
AUDIO_CLUSTER_SECONDS = 10
MAX_AUDIO_OFFSET_SECONDS = 30
_FP_VALUES_PER_SECOND = 37.5

NUM_VISUAL_ANCHORS = 5
SKIP_FIRST_SECONDS = 10
VISUAL_CLUSTER_SECONDS = 10
VISUAL_REQUIRED_MATCHES = 1
VISUAL_FRAME_THRESHOLD = 3 / 9

AUDIO_THRESHOLD = 0.95
AUDIO_REQUIRED_MATCHES = 1
SHORT_VIDEO_THRESHOLD = 120
SHORT_SKIP_FIRST = 0
SHORT_CLUSTER_SECONDS = 5

TEMP_DIR = None

DURATION_PREFERENCE_THRESHOLD = 0.5   # videos shorter than 50% of the longest are deprioritised as KEEP candidates

UPSCALING_CONFIDENCE_THRESHOLD = 0.65
MIN_UPSCALING_ANALYSIS_RESOLUTION = 720

CACHE_DIR = ".dedup_cache"
CACHE_INDEX = os.path.join(CACHE_DIR, "index.json")
CACHE_LOCK = os.path.join(CACHE_DIR, ".lock")
CACHE_VERSION = 2